### ISSUE TITLE
为嘛把全屏去掉了哇。。。

### ISSUE THREAD

**Issue by Veaer** [Darmody/DoubanFMac#4]
感觉全屏还是蛮舒服的。。。

**Comment by Darmody** [comment]
Hi, 感谢使用豆瓣FMac。

我应该漏掉这个快捷键了。。不过为什么要全屏使用呢？

**Comment by Veaer** [comment]
我是志凡安利的。。。习惯性把音乐app单独放在一屏里

**Comment by Darmody** [comment]
哈哈，看来要给潘少发红包了。我会发布一个小版本来修复这个问题的。

**Comment by Veaer** [comment]
谢谢哈

**Comment by Darmody** [comment]
@Veaer 不用把issue关了，我再修复问题后会来关掉的
